# File generated by cwl2click v0.10.1
# timestamp: 2026-10-07T06:28:58.000

__all__ = []

from waterbodies.otsu_impl import execute as otsu_command
from waterbodies.crop_impl import execute as crop_command
from waterbodies.norm_diff_impl import execute as norm_diff_command
from waterbodies.stac_impl import execute as stac_command

from pathlib import Path

import click







# None
__all__.append("waterbodies")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# otsu = "waterbodies.otsu:waterbodies"

@click.group()
def waterbodies() -> None:
    pass



waterbodies.add_command(
    click.Command(
        name="otsu",
        callback=otsu_command,
        help="""Threshold finite NDWI pixels; nonfinite pixels are non-water.""",
        short_help="""Otsu""",
        params=[
            click.Option(
                ["--raster"],
                "raster",
                type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
                multiple=False,
                required=True,
                is_flag=False,
            ),
        ]
    )
)








waterbodies.add_command(
    click.Command(
        name="crop",
        callback=crop_command,
        help="""Crop the data asset selected by EO common band name to a bounding box or polygon.""",
        short_help="""Crop""",
        params=[
            click.Option(
                ["--input-item"],
                "item",
                type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=False, dir_okay=True),
                multiple=False,
                required=True,
                is_flag=False,
                help="""Staged self-contained STAC catalog containing the source Item and bands.""",
            ),
            click.Option(
                ["--aoi"],
                "aoi",
                type=click.STRING,
                multiple=False,
                required=True,
                is_flag=False,
                help="""xmin,ymin,xmax,ymax or GeoJSON polygon in the supplied CRS.""",
            ),
            click.Option(
                ["--epsg"],
                "epsg",
                type=click.STRING,
                multiple=False,
                required=True,
                is_flag=False,
                help="""AOI coordinate reference system, for example EPSG:4326.""",
            ),
            click.Option(
                ["--band"],
                "band",
                type=click.STRING,
                multiple=False,
                required=True,
                is_flag=False,
                help="""EO common band name; green or nir for NDWI.""",
            ),
        ]
    )
)








waterbodies.add_command(
    click.Command(
        name="norm-diff",
        callback=norm_diff_command,
        help="""Calculate (green - nir) / (green + nir) on matching raster grids.""",
        short_help="""Normalized difference""",
        params=[
            click.Option(
                ["--rasters"],
                "rasters",
                type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
                multiple=True,
                required=True,
                is_flag=False,
                help="""Exactly two rasters in green, nir order.""",
            ),
        ]
    )
)








waterbodies.add_command(
    click.Command(
        name="stac",
        callback=stac_command,
        help="""Package the water mask as a validated self-contained STAC catalog.""",
        short_help="""STAC""",
        params=[
            click.Option(
                ["--input-item"],
                "item",
                type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=False, dir_okay=True),
                multiple=False,
                required=True,
                is_flag=False,
            ),
            click.Option(
                ["--water-body"],
                "water_body",
                type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
                multiple=False,
                required=True,
                is_flag=False,
            ),
        ]
    )
)

